### ISSUE TITLE
terminusos Redis state Pending

### ISSUE THREAD

**Issue by bilalbayasut** [beclab/Olares#359]
I've tried to do clean install of terminus os from ubuntu 24.04 (within proxmox) , but got this loop of error
```bash
terminusos Redis State Pending
```

**Comment by pengpeng** [comment]
@bilalbayasut 

Could you locate the ./logs/terminus_install.log file? Sharing it with us would greatly help in identifying the issue.


And If it's convenient, could you please run it

`kubectl describe pod -l 'app=redis,tier=database,version=redis-4.0' -n kubesphere-system`

and show us the result


Thanks

**Comment by bilalbayasut** [comment]
thanks for reply @pengpeng 
now I get this, after redoing it in ubuntu 22.04
```
terminus node pending
```
until it stopped
![image](https://github.com/user-attachments/assets/5ddc52c6-4e85-4b4d-8156-970ae0003f2a)

couldn't find `./logs/terminus_install.log ` , where is it located ?

**Comment by aby913** [comment]
@bilalbayasut 
Could you please tell me the version information you installed? During the installation, our installation package program will be downloaded, and the folder will be named like this: install-wizard. In this directory, there will be logs/terminus_install.log.

**Comment by bilalbayasut** [comment]
@aby913 yup, but no logs found
![image](https://github.com/user-attachments/assets/ede66af7-7115-4f17-b214-4fcddd01a9cf)

**Comment by aby913** [comment]
@bilalbayasut 
the log files for this version are located in /tmp/install_log/logs/termius_install.log

**Comment by bilalbayasut** [comment]
unfortunately no log files @aby913 
![image](https://github.com/user-attachments/assets/3498acb3-e68c-4c24-8f68-dcd05a189f91)

**Comment by pengpeng** [comment]
@bilalbayasut 

We will test the installation issue on Proxmox tomorrow.

**Comment by bilalbayasut** [comment]
Thanks, I'm really eager to use this as my homelab as it looks realy cool, previously been using casaos btw

**Comment by pengpeng** [comment]
We'll release this fix in version 1.8. You can try it out in the latest daily build.

`curl -sSfL https://github.com/beclab/Terminus/releases/download/1.8.0-20240826/install.sh | bash -`
