### ISSUE TITLE
Failure during installation

### ISSUE THREAD

**Issue by ankit16-19** [beclab/Olares#734]
```
root@oxygen:~# curl -fsSL https://olares.sh |  bash -
the KUBE_TYPE env var is not set, defaulting to "k3s"

olares-cli already installed and is the expected version

downloading installation wizard...

current: root
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x7488a0]

goroutine 1 [running]:
go.uber.org/zap.(*SugaredLogger).log(0x0, 0x5, {0xc00016f410?, 0x0?}, {0xc00099fc58?, 0x33ced8b600000000?, 0xc00099fb68?}, {0x0, 0x0, 0x0})
	/home/runner/go/pkg/mod/go.uber.org/zap@v1.27.0/sugar.go:354 +0xa0
go.uber.org/zap.(*SugaredLogger).Fatalf(...)
	/home/runner/go/pkg/mod/go.uber.org/zap@v1.27.0/sugar.go:235
bytetrade.io/web3os/installer/pkg/core/logger.Fatalf(...)
	/home/runner/work/Installer/Installer/pkg/core/logger/logger.go:214
bytetrade.io/web3os/installer/cmd/ctl/os.NewCmdDownloadWizard.func1(0xc000196700?, {0x1fd7ac9?, 0x4?, 0x1fd7acd?})
	/home/runner/work/Installer/Installer/cmd/ctl/os/download.go:48 +0x99
github.com/spf13/cobra.(*Command).execute(0xc000617b08, {0xc00036e080, 0x8, 0x8})
	/home/runner/go/pkg/mod/github.com/spf13/cobra@v1.8.0/command.go:987 +0xab1
github.com/spf13/cobra.(*Command).ExecuteC(0xc000616008)
	/home/runner/go/pkg/mod/github.com/spf13/cobra@v1.8.0/command.go:1115 +0x3ff
github.com/spf13/cobra.(*Command).Execute(0xc0000502c0?)
	/home/runner/go/pkg/mod/github.com/spf13/cobra@v1.8.0/command.go:1039 +0x13
main.main()
	/home/runner/work/Installer/Installer/cmd/main.go:15 +0xd8
```

**Comment by dkeven** [comment]
hi @ankit16-19 , in https://github.com/beclab/Olares/issues/736 you mentioned that you managed to fix the problem & installed Olares successfully at the end, which we're very glad to hear.

Can you tell us what you did specifically to help us better understand the issue that caused the initial failure?

Thanks.

**Comment by ankit16-19** [comment]
hi @dkeven, I was able to install Olares without any issues in my `other` proxmox instance. for this particular instance(uname oxygen).
If i run the install script i get null pointer error or if i try to install `olares-cli olares install` directly i get below error.

```
root@oxygen:~# olares-cli olares install
current: root
Error creating installation runtime: Failed to copy public key to authorized_keys: exit status 127
/bin/sh: 1: sudo: not found
```

**Comment by dkeven** [comment]
> hi @dkeven, I was able to install Olares without any issues in my `other` proxmox instance. for this particular instance(uname oxygen). If i run the install script i get null pointer error or if i try to install `olares-cli olares install` directly i get below error.
> 
> ```
> root@oxygen:~# olares-cli olares install
> current: root
> Error creating installation runtime: Failed to copy public key to authorized_keys: exit status 127
> /bin/sh: 1: sudo: not found
> ```

based on the error message, it seems like the `sudo` command is not installed in your `oxygen` instance, as it supports multiple platform and operating systems, olares-cli needs to use sudo to execute some configuration task, can you execute `apt install sudo` to install it and then try again?

**Comment by darkrain88** [comment]
2024-12-13T12:12:33.043+0800    [A] server: GenerateK3sRegistryConfig success (38.485958ms)
2024-12-13T12:12:36.900+0800    [A] server: EnableK3sService success (3.857153843s)
2024-12-13T12:12:36.958+0800    [A] server: CopyKubeConfig success (58.215596ms)
2024-12-13T12:12:36.959+0800    [A] server: AddMasterTaint(k3s) skipped (157.477µs)
2024-12-13T12:12:37.186+0800    server waiting for node ready
2024-12-13T12:12:47.427+0800    server waiting for node ready
2024-12-13T12:12:57.658+0800    server waiting for node ready
2024-12-13T12:13:07.888+0800    server waiting for node ready
2024-12-13T12:13:18.121+0800    server waiting for node ready
2024-12-13T12:13:28.354+0800    server waiting for node ready
2024-12-13T12:13:38.581+0800    server waiting for node ready

**Comment by dkeven** [comment]
> 2024-12-13T12:12:33.043+0800 [A] server: GenerateK3sRegistryConfig success (38.485958ms) 2024-12-13T12:12:36.900+0800 [A] server: EnableK3sService success (3.857153843s) 2024-12-13T12:12:36.958+0800 [A] server: CopyKubeConfig success (58.215596ms) 2024-12-13T12:12:36.959+0800 [A] server: AddMasterTaint(k3s) skipped (157.477µs) 2024-12-13T12:12:37.186+0800 server waiting for node ready 2024-12-13T12:12:47.427+0800 server waiting for node ready 2024-12-13T12:12:57.658+0800 server waiting for node ready 2024-12-13T12:13:07.888+0800 server waiting for node ready 2024-12-13T12:13:18.121+0800 server waiting for node ready 2024-12-13T12:13:28.354+0800 server waiting for node ready 2024-12-13T12:13:38.581+0800 server waiting for node ready

it seems like the k3s service has not initiated in over a minute, you can check the status of it by executing:
`kubectl get node`
and
`sudo journalctl -xeu k3s`
