### ISSUE TITLE
How to add more machine to my clusters? (same olare)

### ISSUE THREAD

**Issue by ankit16-19** [beclab/Olares#736]
I can find script for terminus but not for the new installation method.
I was able to successfully install olares in to one of my machines.
I want to install into others i.e make it multi cluster.

I can't find any support docs for same.

**Comment by dkeven** [comment]
Hi, we're currently in the process of migrating the miscellaneous shell scripts into a more structured CLI program based on Golang, along with the refactoring of all the related docs.

Unfortunately, for the time being, the legacy scripts, like the one used for adding node, is not compatible with an Olares installed by the new method, but they'll be available as a CLI command in the near future.
